name: generate report
on: 
  workflow_dispatch:
  schedule:
    - cron: "00 15 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: install dependencies
        run: |
          npm install
      - name: otomoto listing
        run: |
          node otomoto.js
      - name: otomoto create html
        run: |
          node json_to_html.js
      - name: generate report
        run: |
          node report.js    
      - name: commit listing and report
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automatic listing and report generated
          file_pattern: '*.json, *.html, *.webp'
  pages-directory-listing:
    needs: generate
    runs-on: ubuntu-latest
    name: directory listing index
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: generate directory listing
        uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: .
      - name: upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'report'
  deploy:
    needs: pages-directory-listing
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
