name: generate report
on: 
  workflow_dispatch:
  schedule:
    - cron: "00 15 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.4
      - name: install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: otomoto listing
        run: |
          python otomoto.py
      - name: otomoto report
        run: |
          python report.py
      - name: commit listing and report
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automatic report generated
          file_pattern: '*.xlsx'
