name: generate report
on: 
  workflow_dispatch:
  schedule:
    - cron: "00 15 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.4
      - name: install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: otomoto listing
        run: |
          python otomoto.py
      - name: otomoto report
        run: |
          python report.py
      - name: commit listing and report
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automatic report generated
  pages-directory-listing:
    runs-on: ubuntu-latest
    name: directory listing index
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: generate directory listing
        uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: report
      - name: upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'report'
  deploy:
    needs: pages-directory-listing
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
          file_pattern: '*.xlsx'
